url: https://g1stavo.me

compass:
  author: ""
  tagline: ""
  include_content: true
  include_analytics: false
  twitter: ""

exclude: ["CNAME", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

markdown: kramdown
highlighter: rouge

permalink: pretty
