# general configuration
url: https://g1stavo.me

# exclude
exclude: ["CNAME", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty
